blueprints/criarconta.py
from flask import *
from db import Usuario
criarconta_bp = Blueprint('criar',__name__,template_folder='templates')

@criarconta_bp.route('/cadastro',methods=['GET','POST'])
def cadastro():

    if request.method =='POST':
        usuario = request.form.get('usuario') ###pegar o nome do form do cadastro que ta como: criar.cadastro
        email = request.form.get('email')
        senha = request.form.get('senha')

        print(usuario,senha)
        Usuario.criar_usuario(usuario,email,senha)
        flash(f'o usuario {usuario} foi criado','success')


    
    return render_template('criar/criar.html')

blueprints/home.py
from flask import *
from db import Usuario


home_bp = Blueprint('home', __name__, template_folder='templates')


def require_login(func):
    def wrapper(*args, **kwargs):
        if 'usuario_id' not in session:
            return redirect(url_for('REGISTRO.registro'))  # Redireciona para o login se não estiver logado
        return func(*args, **kwargs)
    return wrapper

# Função de rota com o nome correto 'pagina_home'
@home_bp.route('/home', endpoint='pagina_home')  # Explicitamente define o nome do endpoint
@require_login
def pagina_home():
    usuario_id = session.get('usuario_id')
    usuario = Usuario.query.get(usuario_id)
    
    return render_template('/home/home.html',usuario = usuario.nome)

blueprints/registro.py
from flask import *
from db import db, Usuario

registro_bp = Blueprint('REGISTRO', __name__, template_folder='templates/home')

@registro_bp.route('/', methods=['GET', 'POST'])
def registro():
    return render_template('registro.html') 

@registro_bp.route('/login', methods=['POST'])
def login():
    if request.method == 'POST':
        usuario = request.form.get('usuario')
        senha = request.form.get('senha')

    #acha o nome do usuario no banco de dados
        user = Usuario.query.filter_by(nome=usuario).first()

    #compara nome e senha 
        if user and user.senha == senha:
            # Armazena o ID do usuário na sessão
            #cria a sessão usando o id do usuario que foi procurado no banco de dados
            session['usuario_id'] = user.id
            flash('Login Realizado Com Sucesso')
            return redirect(url_for('home.pagina_home'))  # Redireciona  para home.pagina_home
        
        else:
            return jsonify({'status': 'error', 'message': 'Login Invalido'}), 401
            
    if request.method == 'GET':
        return render_template('registro.html')

main.py
from flask import *
from blueprints.registro import registro_bp
from blueprints.home import home_bp
from blueprints.criarconta import criarconta_bp
from db import *
import click

app = Flask(__name__)
app.secret_key = '12012109'

app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///banco.db'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False



db.init_app(app)

app.register_blueprint(registro_bp)  # Registra o Blueprint de Registro
app.register_blueprint(home_bp)  # Registra o Blueprint de Home
app.register_blueprint(criarconta_bp)
##rodar as operações: 
@app.cli.command('rodar')
def rodar():
    with app.app_context():
        Usuario.mostrartudo()
        
#pra mostrar todos os usuarios do banco de dados é só escrever no terminal "flask --app main.py rodar"

if __name__ == "__main__":
    app.run(debug=True)

templates/criar/criar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CADASTRO</title>
</head>






{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
    {% for category, message in messages %}
        <div class="alert alert-{{ category }}">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}
{% endwith %}





<body>
    <label for="">CADASTRO DE usuario</label>
    <BR></BR>


    <form action="{{url_for('criar.cadastro')}}" method="post" id="form-cadastro">
    

        <label for="">Coloque o Seu nome de usuario: </label>
        <input type="text" name="usuario">
        <br>
        
        <label for="">Coloque o email:</label>
        <input type="text" name="email">
        <br>
        <label for="">Coloque a senha: </label>
        <input type="text" name="senha">
        <br>
        
        <button type="submit">ENVIAR</button>



    </form>
    
</body>
</html>

templates/home/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=, initial-scale=1.0">
    <title>Bem vindo {{usuario}}</title>
</head>
<body>
    <H1>Bem vindo {{usuario}}</H1>
</body>
</html>

templates/registro.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
</head>
<body>
    <form action="{{ url_for('REGISTRO.login') }}" method="POST" id="form-de-login">
        <input type="text" name="usuario" placeholder="Usuário">
        <input type="password" name="senha" placeholder="Senha">
        <button type="submit">Entrar</button>
        <Label id="mensagem"></Label>
        
    </form>
<br>
<br>
    <a href="{{url_for('criar.cadastro')}}">Criar uma conta</a>

    <script src="/static/js/showmsg.js">



    </script>
    
</body>
</html>